name = "cookiecutter-remix"
main = "app/root.tsx"
compatibility_date = "2022-11-07"
node_compat = true

[env.staging]
d1_databases = [
    { binding = "DB", database_name = "test1", database_id = "024791a8-1a7f-4ac6-ab8d-ce81ec4c5ac6", preview_database_id = "DB" },
]

[env.production]
d1_databases = [
    { binding = "DB", database_name = "test1-prod", database_id = "be39846f-4d04-4c9e-973d-c76a3d51d151" },
]
