name = "cookiecutter-remix"
main = "app/routes/_index.ts"
compatibility_date = "2022-11-07"
node_compat = true

[[d1_databases]]
binding = "DB"
database_name = "test1"
database_id = "024791a8-1a7f-4ac6-ab8d-ce81ec4c5ac6"


