name = "cookiecutter-remix"
main = "app/root.tsx"
compatibility_date = "2022-11-07"
node_compat = true


# CF page does not use wrangler.toml for D1. 
[[d1_databases]]
binding = "DB"
database_name = "cookiecutter-remix-staging"
database_id = "e5528349-f963-4cff-981d-01fd71702d42"
preview_database_id = "DB" 
