name: 'main_cicd'

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  test_matrix:
    strategy:
      matrix:
        flavor: [unit, integration, e2e]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: test
        run: scripts/test.sh ${{matrix.flavor}}

      - name: Vitest Coverage Report
        uses: davelosert/vitest-coverage-report-action@v2.1.1
        with:
          name: '${{matrix.flavor}} test'
          json-summary-path: './cookiecutter_remix/coverage/coverage-summary.json'

  deploy_staging:
    runs-on: ubuntu-latest
    needs: test_matrix
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: deploy_supabase
        run: scripts/deploy_to_supabase.sh staging
        env:
          DATABASE_URL: ${{ secrets.COOKIECUTTER_REMIX_STAGING_DATABASE_URL }}

      - name: deploy_cloudflare
        run: scripts/deploy_to_cloudflare.sh staging
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
