name: 'test'

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  test-cookiecutter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20.9.0
          cache: npm
          cache-dependency-path: "{{cookiecutter.project_slug}}/package-lock.json"

      - name: test
        run: scripts/test.sh
  
